# SwiftLint 공통 설정
# - 현재 단계(제출 전)에서는 개발 생산성을 위해 일부 기준을 완화합니다.

# 검사 제외 경로
excluded:
  - DerivedData

# 한 줄 길이 제한
line_length:
  warning: 200
  error: 300
  ignores_comments: true
  ignores_urls: true

# 팀 내 합의로 비활성화한 규칙
disabled_rules:
  - multiple_closures_with_trailing_closure
  - switch_case_alignment

# 강제 캐스팅은 런타임 위험이 크므로 에러 처리
force_cast:
  severity: error

# 식별자 길이 규칙
identifier_name:
  min_length: 1
  max_length: 60 # 너무 긴 것만 체크

# 함수 파라미터 개수 제한
function_parameter_count:
  warning: 8  # 7개부터 경고
  error: 10   # 10개부터 에러

# 함수 본문 길이 제한
function_body_length:
  warning: 150
  error: 200

# 타입 본문 길이 제한
type_body_length:
  warning: 450
  error: 500

# 순환 복잡도 제한 (제출 일정 고려해 warning 기준 완화)
cyclomatic_complexity:
    warning: 15
    error: 20

file_length:
    warning: 800
    error: 1000
