excluded:
  - DerivedData

line_length:
  warning: 200
  error: 300
  ignores_comments: true
  ignores_urls: true

disabled_rules:
  - multiple_closures_with_trailing_closure

force_cast:
  severity: error
